# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'
vars:
  GREETING: Hello, world!
# 配置 includes，通过 dir 指定子目录路径
includes:
  # 给子 Taskfile 起别名（如 included），dir 指向子目录
  k8s:
    taskfile: ./k8s/Taskfile.yml # 子 Taskfile 路径
    dir: ./k8s # 该 Taskfile 所在目录（关键）
    aliases:
      - k8s
  compose:
    taskfile: ./compose/Taskfile.yml
    dir: ./compose
    aliases:
      - compose
  dockerfiles:
    taskfile: ./dockerfiles/Taskfile.yml
    dir: ./dockerfiles
    aliases:
      - dockerfiles
tasks:
  default:
    desc: Kubernetes Docker Compose Dockerfiles 部署编排
    dir: '{{.TASKFILE_DIR}}' # 强制在当前 Taskfile 所在目录（deploy/）执行
    cmds:
      - pwd # 验证：输出会是 .../project-scripts/deploy/
      - ls # 只会列出 deploy/ 下的文件
    silent: true
