# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'
vars:
  GREETING: Hello, world!
# 配置 includes，通过 dir 指定子目录路径
includes:
  # 给子 Taskfile 起别名（如 included），dir 指向子目录
  github-actions:
    taskfile: ./github-actions/Taskfile.yml # 子 Taskfile 路径
    dir: ./github-actions # 该 Taskfile 所在目录（关键）
    aliases:
      - gh
      - actions
  gitlab-ci:
    taskfile: ./gitlab-ci/Taskfile.yml
    dir: ./gitlab-ci
    aliases:
      - gl
      - gitlab
  jenkins:
    taskfile: ./jenkins/Taskfile.yml
    dir: ./jenkins
    aliases:
      - jenkins
  shared:
    taskfile: ./shared/Taskfile.yml
    dir: ./shared
    aliases:
      - shared
tasks:
  default:
    desc: GitHub Actions GitLab CI Jenkins 共享工具 CI/CD 流水线
    dir: . # 强制在当前 Taskfile 所在目录（ci/）执行
    cmds:
      - pwd # 验证：输出会是 .../project-scripts/ci/
      - ls # 只会列出 ci/ 下的文件
    silent: true
